spring:
  data:
    mongodb:
      database: transport
    repositories:
      enabled: true
logging:
  level:
    com.rafaeltc.dublinbusdata: INFO
    org.springframework.data.mongodb.core:.MongoTemplate: INFO
server:
  port: 7777
  vertx:
    port: 7070